name: Node CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate-kits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      # Detect Python dep files
      - name: Detect Python dep files
        id: pdeps
        shell: bash
        run: |
          shopt -s globstar nullglob
          files=(requirements.txt **/requirements.txt **/pyproject.toml)
          matches=()
          for f in "${files[@]}"; do [ -f "$f" ] && matches+=("$f"); done
          if [ ${#matches[@]} -gt 0 ]; then
            {
              echo "found=true"
              echo "files<<EOF"
              printf '%s\n' "${matches[@]}"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      # Setup Python with cache
      - name: Use Python 3.11 (cached)
        if: steps.pdeps.outputs.found == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: ${{ steps.pdeps.outputs.files }}

      # Setup Python without cache
      - name: Use Python 3.11
        if: steps.pdeps.outputs.found != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Build kits
        run: npm run kits:build

  watcher-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      # Detect Python dep files
      - name: Detect Python dep files
        id: pdeps
        shell: bash
        run: |
          shopt -s globstar nullglob
          files=(requirements.txt **/requirements.txt **/pyproject.toml)
          matches=()
          for f in "${files[@]}"; do [ -f "$f" ] && matches+=("$f"); done
          if [ ${#matches[@]} -gt 0 ]; then
            {
              echo "found=true"
              echo "files<<EOF"
              printf '%s\n' "${matches[@]}"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      # Setup Python with cache
      - name: Use Python 3.11 (cached)
        if: steps.pdeps.outputs.found == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: ${{ steps.pdeps.outputs.files }}

      # Setup Python without cache
      - name: Use Python 3.11
        if: steps.pdeps.outputs.found != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run demo watcher
        run: npm run watcher:demo
